
#ifndef COM_DEFINE_DB_PTN_PATCH_WSUS_H_938EF200_F60B_452A_BD30_A10E8507EDCC
#define COM_DEFINE_DB_PTN_PATCH_WSUS_H_938EF200_F60B_452A_BD30_A10E8507EDCC

//-------------------------------------------------------------------

#define SS_PTN_PATCH_WSUS_STATUS_NONE				0
#define SS_PTN_PATCH_WSUS_STATUS_CONFIRM			1
#define SS_PTN_PATCH_WSUS_STATUS_CHANGE				2
#define SS_PTN_PATCH_WSUS_STATUS_WAIT				3
#define SS_PTN_PATCH_WSUS_STATUS_WAIT_REBOOT		4
#define SS_PTN_PATCH_WSUS_STATUS_FAIL				10

//--------------------------------------------------------------------
#endif	//COM_DEFINE_DB_PTN_PATCH_WSUS_H_938EF200_F60B_452A_BD30_A10E8507EDCC