
#ifndef COM_DEFINE_DB_ORG_HOST_STATUS_PO_H_938EF200_F60B_452A_BD30_A10E8507EDCC
#define COM_DEFINE_DB_ORG_HOST_STATUS_PO_H_938EF200_F60B_452A_BD30_A10E8507EDCC

//-------------------------------------------------------------------
//server type
#define SS_ORG_HOST_STATUS_PO_DRV_TYPE_NOT_USED			0 // 
#define SS_ORG_HOST_STATUS_PO_DRV_TYPE_STOP				1 // 
#define SS_ORG_HOST_STATUS_PO_DRV_TYPE_START			2 // 

#define SS_ORG_HOST_STATUS_PO_RUN_TYPE_NONE				0 // 
#define SS_ORG_HOST_STATUS_PO_RUN_TYPE_DOWNLOAD			1 // 
#define SS_ORG_HOST_STATUS_PO_RUN_TYPE_EXECUTE			2 // 
#define SS_ORG_HOST_STATUS_PO_RUN_TYPE_MAKE_PTN			3 // 

//-------------------------------------------------------------------


#endif	//COM_DEFINE_DB_ORG_HOST_STATUS_PO_H_938EF200_F60B_452A_BD30_A10E8507EDCC