
#ifndef COM_DEFINE_DB_LOG_EVENT_HOST_H_938EF200_F60B_452A_BD30_A10E8507EDCC
#define COM_DEFINE_DB_LOG_EVENT_HOST_H_938EF200_F60B_452A_BD30_A10E8507EDCC

//-------------------------------------------------------------------

#define SS_LOG_EVENT_HOST_SYNC_MODE_NONE					0
#define SS_LOG_EVENT_HOST_SYNC_MODE_AGT						0x00000001
#define SS_LOG_EVENT_HOST_SYNC_MODE_SVR						0x00000002
#define SS_LOG_EVENT_HOST_SYNC_MODE_ALL						(SS_LOG_EVENT_HOST_SYNC_MODE_AGT | SS_LOG_EVENT_HOST_SYNC_MODE_SVR)

//-------------------------------------------------------------------

enum
{
	SS_LOG_EVENT_HOST_DESC_KEY_START_TIME			= 1,
	SS_LOG_EVENT_HOST_DESC_KEY_DOC_DEL_CNT,
	SS_LOG_EVENT_HOST_DESC_KEY_PO_START_USED_UNIT_ID,
	SS_LOG_EVENT_HOST_DESC_KEY_BK_DEL_CNT,
	SS_LOG_EVENT_HOST_DESC_KEY_TYPE,
	SS_LOG_EVENT_HOST_DESC_KEY_OPTION,
	SS_LOG_EVENT_HOST_DESC_KEY_NPM_EC_WUA,
	SS_LOG_EVENT_HOST_DESC_KEY_END_TIME,
};

//--------------------------------------------------------------------


#endif	//COM_DEFINE_DB_LOG_EVENT_H_938EF200_F60B_452A_BD30_A10E8507EDCC